[workspace]
authors = ["Satoshi Imamura <satoshi.jb@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "NeuroLM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = "==2.5.0"
torchvision = "==0.20.0"
torchaudio = "==2.5.0"
pytorch-cuda = "12.4.*"
transformers = ">=4.52.3,<5"
datasets = "==2.21.0"
tiktoken = ">=0.9.0,<0.10"
wandb = ">=0.20.1,<0.21"
h5py = ">=3.13.0,<4"
einops = ">=0.8.1,<0.9"
pandas = ">=2.2.3,<3"
scikit-learn = ">=1.6.1,<2"
huggingface_hub = ">=0.31.4,<0.32"
tqdm = ">=4.67.1,<5"
ruff = ">=0.12.0,<0.13"
python = "3.12.*"
numpy = ">=2.3.0,<3"

[pypi-dependencies]
mne = ">=1.9.0, <2"

